---
- include_vars: "{{ item }}"
  with_items:
    - group_vars/hadoop
    - group_vars/gobblin

- name: Check gobblin installation
  stat: path="/opt/{{ gobblin_dir }}"
  register: gobblin_installed

- name: Download gobblin archive
  get_url:
    url: "{{ gobblin_url }}"
    dest: "/tmp/{{ gobblin_base_file }}.tar.gz"
  when: gobblin_installed.stat.exists == false

- name: Unarchive gobblin
  unarchive:
    src: "/tmp/{{ gobblin_base_file }}.tar.gz"
    dest: /opt
    remote_src: True
  when: gobblin_installed.stat.exists == false

- name: Create hadoop config directory
  file: path=/etc/hadoop state=directory

- name: Install hadoop core configuration
  template: src=templates/core-site.xml.j2 dest=/etc/hadoop/core-site.xml

- name: Install hadoop hdfs configuration
  template: src=templates/hdfs-site.xml.j2 dest=/etc/hadoop/hdfs-site.xml

- name: Install hadoop yarn configuration
  template: src=templates/yarn-site.xml.j2 dest=/etc/hadoop/yarn-site.xml

- name: Install hadoop mapred configuration
  template: src=templates/mapred-site.xml.j2 dest=/etc/hadoop/mapred-site.xml
