---
- name: update packages (deb)
  apt: upgrade=dist
  when: ansible_os_family == "Debian" and force_pkg_update == true

- name: update packages (yum)
  yum: name=* state=latest
  when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "yum" and force_pkg_update == true

- name: update packages (dnf)
  command: dnf -y update
  when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "dnf" and force_pkg_update == true

- name: install packages
  command: dnf -y install libselinux-python python2-dnf
  when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "dnf" and force_pkg_update == true

- name: Disable service initial-setup
  systemd: name=initial-setup enabled=no state=stopped
  when:
    - ansible_service_mgr == 'systemd'
    - ansible_architecture == "armv7l"
    - ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Disable service firewalld
  systemd: name=firewalld enabled=no state=stopped
  when:
    - ansible_service_mgr == 'systemd'
    - ansible_os_family == "RedHat"

- name: Set hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644

- name: Set hostname
  hostname:
    name: "{{ ansible_host }}"

- stat: path=/opt/jdk{{ jdk_version_file }}
  register: jdk_install_rules

- name: download Oracle JDK (x64)
  get_url:
    url:     "{{ jdk_url_base }}/{{ jdk_file_base }}-linux-x64.tar.gz"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "/{{ jdk_extract_dir }}/{{ jdk_file_base }}-linux-x64.tar.gz"
  when:
    - jdk_install_rules.stat.exists == false
    - ansible_architecture == "x86_64"

- name: unarchive JDK (x64)
  unarchive:
    src: "/{{ jdk_extract_dir }}/{{ jdk_file_base }}-linux-x64.tar.gz"
    dest: /opt
    remote_src: True
  when:
    - jdk_install_rules.stat.exists == false
    - ansible_architecture == "x86_64"

- name: install oracle jdk package (deb)
  package:
    name: oracle-java8-jdk
    state: latest
  when: ansible_os_family == "Debian" and ansible_architecture == "armv7l"

- name: install collectd package
  package:
    name: collectd
    state: latest

- name: enable collectd
  service:
    name: collectd
    state: started
    enabled: yes

- name: install ruby1.9.3
  package:
    name: ruby1.9.3
    state: latest

- name: install ruby development
  package:
    name: ruby-dev
    state: latest

- name: install fluentd
  gem:
    name: fluentd
    version: 0.12.34
    state: present
