---
- include_vars: group_vars/hadoop

- name: Check hadoop installation
  stat: path=/opt/{{ hadoop_file_base }}
  register: hadoop_install_rules

- name: Check hadoop namenode created
  stat: path={{ hdfs_tmp_dir }}/dfs/name/current
  register: hdfs_namenode_dir

- name: Download hadoop archive
  get_url:
    url: "{{ hadoop_url }}"
    dest: "/tmp/{{ hadoop_file_base }}.tar.gz"
  when: hadoop_install_rules.stat.exists == false

- name: Unarchive hadoop
  unarchive:
    src: "/tmp/{{ hadoop_file_base }}.tar.gz"
    dest: /opt
    remote_src: True
  when: hadoop_install_rules.stat.exists == false

- name: Configure yarn rm
  template: src=templates/yarn-site.xml.j2 dest=/opt/{{ hadoop_file_base }}/etc/hadoop/yarn-site.xml

- name: Format yarn store
  environment:
    - JAVA_HOME: /opt/jdk{{ jdk_version_file }}
  command: /opt/{{ hadoop_file_base }}/bin/yarn resourcemanager -format-state-store
  when: hdfs_namenode_dir.stat.exists == false

- name: Create yarn resourcemanager unit file
  template: src=templates/yarn_rm.service.j2 dest=/lib/systemd/system/yarn_rm.service
  when: ansible_service_mgr == 'systemd'
  notify:
    - Reload systemctl
    - Restart yarn_rm service

- name: Enable service yarn_rm
  systemd: name=yarn_rm enabled=yes state=started daemon-reload=yes
  when: ansible_service_mgr == 'systemd'

- name: Restart yarn_rm service
  service: name=yarn_rm state=restarted
