---
- include_vars: group_vars/opentsdb
- include_vars: group_vars/hbase

- name: Check hbase installation
  stat: path=/opt/{{ hbase_file_base }}
  register: hbase_installed

- name: Download hbase archive
  get_url:
    url: "{{ hbase_url }}"
    dest: "/tmp/{{ hbase_file_base }}.tar.gz"
    tmp_dest: /tmp

- name: Unarchive hbase
  unarchive:
    src: "/tmp/{{ hbase_file_base }}.tar.gz"
    dest: /opt
    remote_src: True
  when: hbase_installed.stat.exists == false

- name: Create hbase configuration
  template: src=templates/hbase-site.xml.j2 dest=/opt/{{ hbase_file_base }}/conf/hbase-site.xml

- name: install crudini
  dnf:
    name: crudini
    state: present

- name: install opentsdb
  dnf:
    name: "{{ opentsdb_url }}"
    state: present
  when: ansible_pkg_mgr == 'dnf'

- name: create opentsdb tables
  shell: env JAVA_HOME=/opt/jdk{{ jdk_version_file }} COMPRESSION=NONE HBASE_HOME=/opt/{{ hbase_file_base }} /usr/share/opentsdb/tools/create_table.sh

- name: Enable service opentsdb
  systemd: name=opentsdb enabled=yes state=started daemon-reload=yes
  when: ansible_service_mgr == 'systemd'

- name: Configure opentsdb
  shell: crudini --set /etc/opentsdb/opentsdb.conf "" tsd.storage.hbase.zk_quorum "{{ groups['zookeeper']|join(',')}}"
  notify:
    - Restart opentsdb service
